- hosts: webservers
  become: yes
  tasks:
    - name: update ubuntu
      update_cache: yes
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html